name: task-trail

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - react-express
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
        - ./backend/.env
    ports:
      - 3000:3000
    networks:
      - react-express
      - express-mongodb
    restart: always
    depends_on:
      - mongodb

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - express-mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass12345
      ME_CONFIG_MONGODB_URL: mongodb://root:pass12345@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./db/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - mongodb-data:/data/db
    networks:
      - express-mongodb
    ports:
      - 27017:27017
    restart: always

networks:
  react-express:
  express-mongodb:


volumes:
  mongodb-data:
    name: mongodb-data
